action.CreateOrJumpToJimmerDtoFile.text=JimmerDto File
action.CreateOrJumpToJimmerDtoFile.description=Create new JimmerDTO file or jump to it if exists
action.InsertEntityPropsToDto.text=Insert Entity Props to Here
action.InsertEntityPropsToDto.description=Insert all props from the associated entity to current cursor position
notification.group.jimmerdto.notification.group=JimmerDTO notification