{
  parserClass="net.fallingangel.jimmerdto.language.parser.DTOParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="DTO"
  psiImplClassSuffix="Impl"
  psiPackage="net.fallingangel.jimmerdto.language.psi"
  psiImplPackage="net.fallingangel.jimmerdto.language.psi.impl"

  elementTypeHolderClass="net.fallingangel.jimmerdto.language.psi.DTOTypes"
  elementTypeClass="net.fallingangel.jimmerdto.language.psi.DTOElementType"
  tokenTypeClass="net.fallingangel.jimmerdto.language.psi.DTOTokenType"
}

simpleFile ::= item_*

private item_ ::= (property|COMMENT|CRLF)

property ::= (KEY? SEPARATOR VALUE?) | KEY
